language: node_js
node_js:
  - "stable"
cache: npm

notification:
  email: false

before_install:
  - cd client-side

install:
  - npm ci

env: REACT_APP_ENV=production
  REACT_APP_PRODUCTION_API_BASE_URL=http://nciserver-env.m2ecpqkmqs.ap-south-1.elasticbeanstalk.com/

script:
  - npm run format
  - npm run test
  - npm run build
