language: node_js
node_js:
  - "stable"
cache: npm

notification:
  email: false

before-install:
  - cd client-side

install:
  - npm ci

script:
  - npm run format
  - npm run test
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "ncimages.tech"
  local_dir: build
  skip_cleanup: true
