version: '3'

services: 

    backend:
        # build: ./server-side
        # container_name: image-search:backend
        image: image-search:backend
        command: ["node", "app.js"]
        volumes: 
            - ./server-side:/home/node/backend
        ports: 
            - "8000:8000"

    
    frontend:
        depends_on: 
            - backend
        build: ./client-side
        container_name: image-search:frontend
        volumes: 
            - ./client-side/build:/usr/share/nginx/html
        ports: 
            - "8080:80"