version: '3'

services: 

    backend:
        build: ./server-side
        container_name: NCI-backend
        env_file: ./server-side/.env
        command: ["npm", "start"]
        ports: 
            - 9000:9000
        
        stdin_open: true
    

    frontend:
        depends_on: 
            - backend
        build: ./client-side
        container_name: NCI-frontend
        env_file: ./client-side/.env
        ports: 
            - 3000:3000
        
        # for enabling hot reloading
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true