export const TITLE = 'No Copyright Images'
export const SOCIAL_GITHUB = 'https://github.com/msk4862'
export const SOCIAL_LINKEDIN = 'https://www.linkedin.com/in/msk4862'
export const SOCIAL_FACEBOOK = 'https://www.facebook.com/md.shoaib.4862'
export const SOCIAL_TWITTER = 'https://twitter.com/msk4862'
